openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                x-content-type: application/json
      x-swagger-router-controller: Default
  /prime/{number}:
    get:
      summary: Is Prime Number
      operationId: is_prime_number_prime__number__get
      parameters:
      - name: number
        in: path
        required: true
        style: simple
        explode: false
        schema:
          title: Number
          type: integer
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                x-content-type: application/json
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-swagger-router-controller: Default
  /picture/invert:
    get:
      summary: Inverse Picture
      operationId: inverse_picture_picture_invert_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                x-content-type: application/json
      x-swagger-router-controller: Default
  /login:
    get:
      summary: User
      operationId: user_login_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                x-content-type: application/json
      security:
      - HTTPBasic: []
      x-swagger-router-controller: Default
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
